server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/returnaction/spring-config-microservices-config.git
          clone-on-start: true
          default-label: master